# Generates lib/app/localization/translations/wide.dart
# Run from VoteBanker_Frontend.

langs = [
    "af", "am", "ar", "as", "az", "bn", "bg", "my", "ca", "zh", "hr", "cs", "da",
    "nl", "et", "fil", "fi", "fr", "ka", "de", "el", "gu", "ha", "he", "hu", "is",
    "ig", "id", "ga", "it", "ja", "kk", "km", "ko", "lo", "lv", "lt", "ms", "mr",
    "mn", "ne", "no", "or", "ps", "fa", "pl", "pt", "pa", "ro", "ru", "sr", "si",
    "sk", "sl", "so", "es", "sw", "sv", "th", "tr", "uk", "ur", "uz", "vi", "cy",
    "yo", "zu",
]

# key -> translations in the same order as langs
packs = {}


def add(key, values):
    if len(values) != len(langs):
        raise SystemExit(f"{key}: {len(values)} != {len(langs)}")
    packs[key] = values


# The strings below follow `langs` order exactly.
add("basicProfile", "Leierprofiel|የመሪ መገለጫ|ملف القائد|নেতাৰ প্ৰ’ফাইল|Lider profili|নেতার প্রোফাইল|Профил на лидера|ခေါင်းဆောင်ပရိုဖိုင်|Perfil del líder|领袖资料|Profil vođe|Profil lídra|Lederprofil|Leidersprofiel|Juhi profiil|Profile ng Lider|Johtajan profiili|Profil du leader|ლიდერის პროფილი|Führungsprofil|Προφίλ ηγέτη|નેતા પ્રોફાઇલ|Bayanin shugaba|פרופיל מנהיג|Vezetői profil|Prófíll leiðtoga|Profaịlụ onye ndu|Profil Pemimpin|Próifíl ceannaire|Profilo del leader|リーダープロフィール|Көшбасшы профилі|ប្រវត្តិរូបអ្នកដឹកនាំ|리더 프로필|ໂປຣໄຟລ໌ຜູ້ນຳ|Līdera profils|Lyderio profilis|Profil Pemimpin|नेता प्रोफाइल|Удирдагчийн профайл|नेता प्रोफाइल|Lederprofil|ନେତା ପ୍ରୋଫାଇଲ୍|د مشر پروفایل|نمایه رهبر|Profil lidera|Perfil do líder|ਲੀਡਰ ਪ੍ਰੋਫ਼ਾਈਲ|Profil de lider|Профиль лидера|Профил лидера|නායක පැතිකඩ|Profil lídra|Profil vodje|Astaanta hoggaamiyaha|Perfil del líder|Wasifu wa kiongozi|Ledareprofil|โปรไฟล์ผู้นำ|Lider profili|Профіль лідера|لیڈر پروفائل|Lider profili|Hồ sơ lãnh đạo|Proffil arweinydd|Profaili oludari|Iphrofayela yomholi".split("|"))
add("profileDescription", "Vertel ons ’n bietjie oor jou leierskap|ስለ አመራርዎ ትንሽ ይንገሩን|أخبرنا قليلاً عن قيادتك|আপোনাৰ নেতৃত্বৰ বিষয়ে অলপ কওক|Liderliyiniz haqqında bir az danışın|আপনার নেতৃত্ব সম্পর্কে একটু বলুন|Разкажете малко за вашето лидерство|သင့်ခေါင်းဆောင်မှုအကြောင်း အနည်းငယ်ပြောပါ|Explica’ns una mica el teu lideratge|介绍一下你的领导工作|Recite nam malo o svom vodstvu|Řekněte nám něco o svém vedení|Fortæl os lidt om dit lederskab|Vertel ons iets over je leiderschap|Rääkige veidi oma juhtimisest|Ikuwento ang iyong pamumuno|Kerro hieman johtajuudestasi|Parlez-nous un peu de votre leadership|მოგვიყევით თქვენს ლიდერობაზე|Erzählen Sie uns etwas über Ihre Führung|Πείτε μας λίγα για την ηγεσία σας|તમારા નેતૃત્વ વિશે થોડું કહો|Faɗa mana kaɗan game da jagorancinku|ספרו לנו מעט על המנהיגות שלכם|Meséljen egy kicsit a vezetéséről|Segðu okkur lítillega frá forystu þinni|Gwaa anyị obere ihe gbasara ndu gị|Ceritakan sedikit tentang kepemimpinan Anda|Inis dúinn beagán faoi do cheannaireacht|Raccontaci un po’ della tua leadership|あなたのリーダーシップについて教えてください|Көшбасшылығыңыз туралы айтыңыз|ប្រាប់យើងបន្តិចអំពីភាពជាអ្នកដឹកនាំរបស់អ្នក|당신의 리더십에 대해 조금 알려 주세요|ບອກພວກເຮົາເລັກນ້ອຍກ່ຽວກັບການນຳຂອງທ່ານ|Pastāstiet mazliet par savu vadību|Papasakokite šiek tiek apie savo lyderystę|Ceritakan sedikit tentang kepimpinan anda|तुमच्या नेतृत्वाबद्दल थोडे सांगा|Удирдан чиглүүлэлтийнхээ тухай ярина уу|आफ्नो नेतृत्वबारे अलिकति भन्नुहोस्|Fortell oss litt om lederskapet ditt|ଆପଣଙ୍କ ନେତୃତ୍ୱ ବିଷୟରେ ଟିକେ କୁହନ୍ତୁ|د خپل مشرتابه په اړه لږ راته ووایاست|کمی از رهبری خود بگویید|Opowiedz nam trochę o swoim przywództwie|Conte um pouco sobre a sua liderança|ਆਪਣੀ ਅਗਵਾਈ ਬਾਰੇ ਥੋੜ੍ਹਾ ਦੱਸੋ|Spuneți-ne puțin despre conducerea dvs.|Расскажите немного о вашем лидерстве|Реците нам мало о свом вођству|ඔබේ නායකත්වය ගැන මඳක් කියන්න|Povedzte nám niečo o svojom vedení|Povejte nam nekaj o svojem vodenju|Noo na wax yar ka sheeg hoggaamintaada|Cuéntanos un poco sobre tu liderazgo|Tuambie kidogo kuhusu uongozi wako|Berätta lite om ditt ledarskap|เล่าให้เราฟังเล็กน้อยเกี่ยวกับความเป็นผู้นำของคุณ|Liderliğiniz hakkında biraz anlatın|Розкажіть трохи про ваше лідерство|اپنی قیادت کے بارے میں تھوڑا بتائیں|Yetakchiligingiz haqida biroz gapiring|Hãy kể một chút về vai trò lãnh đạo của bạn|Dywedwch ychydig am eich arweinyddiaeth|Sọ fun wa diẹ nipa aṣáájú rẹ|Sitshele kancane ngobuholi bakho".split("|"))
add("fullName", "Leiernaam|የመሪ ስም|اسم القائد|নেতাৰ নাম|Liderin adı|নেতার নাম|Име на лидера|ခေါင်းဆောင်အမည်|Nom del líder|领袖姓名|Ime vođe|Jméno lídra|Ledernavn|Naam van de leider|Juhi nimi|Pangalan ng lider|Johtajan nimi|Nom du leader|ლიდერის სახელი|Name der Führungskraft|Όνομα ηγέτη|નેતાનું નામ|Sunan shugaba|שם המנהיג|Vezető neve|Nafn leiðtoga|Aha onye ndu|Nama pemimpin|Ainm an cheannaire|Nome del leader|リーダー名|Көшбасшы аты|ឈ្មោះអ្នកដឹកនាំ|리더 이름|ຊື່ຜູ້ນຳ|Līdera vārds|Lyderio vardas|Nama pemimpin|नेत्याचे नाव|Удирдагчийн нэр|नेताको नाम|Ledernavn|ନେତାଙ୍କ ନାମ|د مشر نوم|نام رهبر|Imię lidera|Nome do líder|ਲੀਡਰ ਦਾ ਨਾਮ|Numele liderului|Имя лидера|Име лидера|නායකයාගේ නම|Meno lídra|Ime vodje|Magaca hoggaamiyaha|Nombre del líder|Jina la kiongozi|Ledarnamn|ชื่อผู้นำ|Lider adı|Ім’я лідера|لیڈر کا نام|Lider ismi|Tên lãnh đạo|Enw’r arweinydd|Orukọ oludari|Igama lomholi".split("|"))
add("photo", "Foto|ፎቶ|صورة|ফটো|Foto|ছবি|Снимка|ဓာတ်ပုံ|Foto|照片|Fotografija|Fotografie|Foto|Foto|Foto|Larawan|Kuva|Photo|ფოტო|Foto|Φωτογραφία|ફોટો|Hoto|תמונה|Fotó|Mynd|Foto|Foto|Grianghraf|Foto|写真|Фото|រូបថត|사진|ຮູບ|Foto|Nuotrauka|Foto|फोटो|Зураг|फोटो|Foto|ଫଟୋ|انځور|عکس|Zdjęcie|Foto|ਫੋਟੋ|Fotografie|Фото|Фотографија|ඡායාරූපය|Fotografia|Fotografija|Sawir|Foto|Picha|Foto|รูปภาพ|Fotoğraf|Фото|تصویر|Surat|Ảnh|Llun|Fọto|Isithombe".split("|"))
add("addPhoto", "Voeg foto by|ፎቶ ያክሉ|إضافة صورة|ফটো যোগ কৰক|Foto əlavə et|ছবি যোগ করুন|Добавете снимка|ဓာတ်ပုံထည့်ရန်|Afegeix una foto|添加照片|Dodaj fotografiju|Přidat fotografii|Tilføj foto|Foto toevoegen|Lisa foto|Magdagdag ng larawan|Lisää kuva|Ajouter une photo|ფოტოს დამატება|Foto hinzufügen|Προσθήκη φωτογραφίας|ફોટો ઉમેરો|Ƙara hoto|הוספת תמונה|Fotó hozzáadása|Bæta við mynd|Tinye foto|Tambah foto|Cuir grianghraf leis|Aggiungi foto|写真を追加|Фото қосу|បន្ថែមរូបថត|사진 추가|ເພີ່ມຮູບ|Pievienot foto|Pridėti nuotrauką|Tambah foto|फोटो जोडा|Зураг нэмэх|फोटो थप्नुहोस्|Legg til foto|ଫଟୋ ଯୋଡନ୍ତୁ|انځور زیات کړئ|افزودن عکس|Dodaj zdjęcie|Adicionar foto|ਫੋਟੋ ਜੋੜੋ|Adaugă fotografie|Добавить фото|Додај фотографију|ඡායාරූපය එක් කරන්න|Pridať fotografiu|Dodaj fotografijo|Ku dar sawir|Añadir foto|Ongeza picha|Lägg till foto|เพิ่มรูปภาพ|Fotoğraf ekle|Додати фото|تصویر شامل کریں|Surat qo‘shish|Thêm ảnh|Ychwanegu llun|Fi fọto kun|Engeza isithombe".split("|"))
add("changePhoto", "Verander foto|ፎቶ ይቀይሩ|تغيير الصورة|ফটো সলনি কৰক|Fotonu dəyiş|ছবি পরিবর্তন করুন|Сменете снимката|ဓာတ်ပုံပြောင်းရန်|Canvia la foto|更换照片|Promijeni fotografiju|Změnit fotografii|Skift foto|Foto wijzigen|Muuda fotot|Palitan ang larawan|Vaihda kuva|Changer la photo|ფოტოს შეცვლა|Foto ändern|Αλλαγή φωτογραφίας|ફોટો બદલો|Canja hoto|החלפת תמונה|Fotó módosítása|Skipta um mynd|Gbanwee foto|Ganti foto|Athraigh an grianghraf|Cambia foto|写真を変更|Фотоны ауыстыру|ប្តូររូបថត|사진 변경|ປ່ຽນຮູບ|Mainīt foto|Keisti nuotrauką|Tukar foto|फोटो बदला|Зураг солих|फोटो बदल्नुहोस्|Bytt foto|ଫଟୋ ବଦଳାନ୍ତୁ|انځور بدل کړئ|تغییر عکس|Zmień zdjęcie|Alterar foto|ਫੋਟੋ ਬਦਲੋ|Schimbă fotografia|Сменить фото|Промени фотографију|ඡායාරූපය වෙනස් කරන්න|Zmeniť fotografiu|Spremeni fotografijo|Beddel sawirka|Cambiar foto|Badilisha picha|Byt foto|เปลี่ยนรูปภาพ|Fotoğrafı değiştir|Змінити фото|تصویر بدلیں|Suratni almashtirish|Đổi ảnh|Newid llun|Yi fọto pada|Shintsha isithombe".split("|"))
add("assemblyConstituency", "Vergaderingkiesafdeling|የምክር ቤት ክልል|الدائرة التشريعية|বিধানসভা সমষ্টি|Məclis dairəsi|বিধানসভা কেন্দ্র|Избирателен район|လွှတ်တော်မဲဆန္ဒနယ်|Circumscripció|议会选区|Izborni okrug|Volební obvod|Valgkreds|Kiesdistrict|Valimisringkond|Distrito ng kapulungan|Vaalipiiri|Circonscription|საარჩევნო ოლქი|Wahlkreis|Εκλογική περιφέρεια|વિધાનસભા મતવિસ્તાર|Yankin majalisa|אזור בחירה|Választókerület|Kjördæmi|Mpaghara ụlọ omebe iwu|Daerah pemilihan|Toghcheantar|Collegio elettorale|選挙区|Сайлау округі|មណ្ឌលបោះឆ្នោត|선거구|ເຂດເລືອກຕັ້ງ|Vēlēšanu apgabals|Rinkimų apygarda|Kawasan pilihan raya|विधानसभा मतदारसंघ|Сонгуулийн тойрог|सभा निर्वाचन क्षेत्र|Valgkrets|ବିଧାନସଭା କ୍ଷେତ୍ର|ټاکنیزه حوزه|حوزه انتخابیه|Okręg wyborczy|Circunscrição|ਵਿਧਾਨ ਸਭਾ ਹਲਕਾ|Circumscripție|Избирательный округ|Изборна јединица|මැතිවරණ කොට්ඨාසය|Volebný obvod|Volilna enota|Degmada doorashada|Circunscripción|Eneo la uchaguzi|Valkrets|เขตเลือกตั้ง|Seçim bölgesi|Виборчий округ|انتخابی حلقہ|Saylov okrugi|Khu vực bầu cử|Ethalwch|Agbegbe idibo|Isifunda sokhetho".split("|"))
add("partNo", "Hokkie nommer|የቡዝ ቁጥር|رقم المركز|বুথ নম্বৰ|Məntəqə nömrəsi|বুথ নম্বর|Номер на секция|မဲရုံနံပါတ်|Número de mesa|投票站编号|Broj biračkog mjesta|Číslo okrsku|Valgstedsnummer|Stembureaunummer|Jaoskonna number|Numero ng presinto|Äänestyspaikan numero|Numéro de bureau|უბნის ნომერი|Wahlbezirknummer|Αριθμός τμήματος|બૂથ નંબર|Lambar rumfar zaɓe|מספר קלפי|Szavazóköri szám|Kjörstaðarnúmer|Nọmba ebe ntuli|Nomor bilik|Uimhir an bhoth|Numero del seggio|投票所番号|Учаске нөмірі|លេខប៉ុស្តិ៍|투표소 번호|ເລກຫ້ອງຫຼຸດ|Iecirknis numurs|Apylinkės numeris|Nombor pusat|बूथ क्रमांक|Салбарын дугаар|बुथ नम्बर|Valglokalenummer|ବୂଥ୍ ନମ୍ବର|د مرکز شمېره|شماره صندوق|Numer obwodu|Número da seção|ਬੂਥ ਨੰਬਰ|Număr secție|Номер участка|Број бирачког места|කූඩු අංකය|Číslo okrsku|Številka volišča|Lambarka goobta|Número de mesa|Nambari ya kituo|Valllokalnummer|หมายเลขหน่วยเลือกตั้ง|Sandık numarası|Номер дільниці|بوث نمبر|Uchastka raqami|Số bàn bỏ phiếu|Rhif y bwth|Nọmba ibudo|Inombolo yesitandi".split("|"))
add("partName", "Hokkie naam|የቡዝ ስም|اسم المركز|বুথৰ নাম|Məntəqənin adı|বুথের নাম|Име на секция|မဲရုံအမည်|Nom de la mesa|投票站名称|Naziv biračkog mjesta|Název okrsku|Valgstedsnavn|Naam stembureau|Jaoskonna nimi|Pangalan ng presinto|Äänestyspaikan nimi|Nom du bureau|უბნის სახელი|Name des Wahlbezirks|Όνομα τμήματος|બૂથનું નામ|Sunan rumfar zaɓe|שם הקלפי|Szavazókör neve|Heiti kjörstaðar|Aha ebe ntuli|Nama bilik|Ainm an bhoth|Nome del seggio|投票所名|Учаске атауы|ឈ្មោះប៉ុស្តិ៍|투표소 이름|ຊື່ຫ້ອງຫຼຸດ|Iecirkņa nosaukums|Apylinkės pavadinimas|Nama pusat|बूथचे नाव|Салбарын нэр|बुथको नाम|Valglokalenavn|ବୂଥ୍ ନାମ|د مرکز نوم|نام صندوق|Nazwa obwodu|Nome da seção|ਬੂਥ ਦਾ ਨਾਮ|Numele secției|Название участка|Назив бирачког места|කූඩුවේ නම|Názov okrsku|Ime volišča|Magaca goobta|Nombre de la mesa|Jina la kituo|Valllokalens namn|ชื่อหน่วยเลือกตั้ง|Sandık adı|Назва дільниці|بوث کا نام|Uchastka nomi|Tên bàn bỏ phiếu|Enw’r bwth|Orukọ ibudo|Igama lesitandi".split("|"))
add("organization", "Party|ፓርቲ|الحزب|দল|Partiya|দল|Партия|ပါတီ|Partit|政党|Stranka|Strana|Parti|Partij|Partei|Partido|Puolue|Parti|პარტია|Partei|Κόμμα|પક્ષ|Jam’iyya|מפלגה|Párt|Flokkur|Patị|Partai|Páirtí|Partito|政党|Партия|គណបក្ស|정당|ພັກ|Partija|Partija|Parti|पक्ष|Нам|पार्टी|Parti|ଦଳ|ګوند|حزب|Partia|Partido|ਪਾਰਟੀ|Partid|Партия|Странка|පක්ෂය|Strana|Stranka|Xisbi|Partido|Chama|Parti|พรรค|Parti|Партія|پارٹی|Partiya|Đảng|Plaid|Ẹgbẹ|Iqembu".split("|"))
add("designation", "Amp|የሥራ መደብ|المنصب|পদবী|Vəzifə|পদবি|Длъжност|ရာထူး|Càrrec|职务|Funkcija|Funkce|Stilling|Functie|Amet|Katungkulan|Tehtävä|Fonction|თანამდებობა|Funktion|Θέση|હોદ્દો|Matsayi|תפקיד|Beosztás|Titill|Ọkwa|Jabatan|Post|Incarico|役職|Лауазым|តួនាទី|직책|ຕຳແໜ່ງ|Amats|Pareigos|Jawatan|पद|Албан тушаал|पद|Stilling|ପଦବୀ|دنده|سمت|Stanowisko|Cargo|ਅਹੁਦਾ|Funcție|Должность|Функција|තනතුර|Funkcia|Funkcija|Jagada|Cargo|Cheo|Befattning|ตำแหน่ง|Görev|Посада|عہدہ|Lavozim|Chức vụ|Swydd|Ipo|Isikhundla".split("|"))
add("country", "Land|ሀገር|الدولة|দেশ|Ölkə|দেশ|Държава|နိုင်ငံ|País|国家|Država|Země|Land|Land|Riik|Bansa|Maa|Pays|ქვეყანა|Land|Χώρα|દેશ|Ƙasa|מדינה|Ország|Land|Obodo|Negara|Tír|Paese|国|Ел|ប្រទេស|국가|ປະເທດ|Valsts|Šalis|Negara|देश|Улс|देश|Land|ଦେଶ|هېواد|کشور|Kraj|País|ਦੇਸ਼|Țară|Страна|Држава|රට|Krajina|Država|Dalka|País|Nchi|Land|ประเทศ|Ülke|Країна|ملک|Mamlakat|Quốc gia|Gwlad|Orilẹ|Izwe".split("|"))
add("stateRegion", "Staat|ክልል|الولاية|ৰাজ্য|Ştat|রাজ্য|Област|ပြည်နယ်|Estat|州/邦|Pokrajina|Stát|Stat|Staat|Osariik|Lalawigan|Osavaltio|État|რეგიონი|Bundesland|Περιφέρεια|રાજ્ય|Jiha|מדינה|Állam|Fylki|Steeti|Provinsi|Stát|Stato|州|Облыс|ខេត្ត|주|ແຂວງ|Štats|Valstija|Negeri|राज्य|Муж|प्रदेश|Delstat|ରାଜ୍ୟ|ولایت|ایالت|Województwo|Estado|ਰਾਜ|Stat|Штат|Покрајина|පළාත|Kraj|Regija|Gobol|Estado|Jimbo|Delstat|รัฐ|Eyalet|Область|ریاست|Viloyat|Tỉnh/Bang|Sir|Ipinle|Isifundazwe".split("|"))
add("constituency", "Distrik|ወረዳ|المنطقة|জিলা|Rayon|জেলা|Община|ခရိုင်|Districte|区/县|Okrug|Okres|Distrikt|District|Piirkond|Distrito|Piiri|District|რაიონი|Bezirk|Περιοχή|જિલ્લો|Gunduma|מחוז|Járás|Hérað|Mpaghara|Kabupaten|Ceantar|Distretto|地区|Аудан|ស្រុក|구/군|ເມືອງ|Rajons|Rajonas|Daerah|जिल्हा|Дүүрэг|जिल्ला|Distrikt|ଜିଲ୍ଲା|ولسوالۍ|شهرستان|Powiat|Distrito|ਜ਼ਿਲ੍ਹਾ|District|Район|Округ|දිස්ත්‍රික්කය|Okres|Okraj|Degmo|Distrito|Wilaya|Distrikt|เขต|İlçe|Район|ضلع|Tuman|Quận/Huyện|Dosbarth|Agbegbe|Isifunda".split("|"))
add("publicContact", "Kontaknommer|የመገናኛ ቁጥር|رقم الاتصال|যোগাযোগ নম্বৰ|Əlaqə nömrəsi|যোগাযোগ নম্বর|Телефон за контакт|ဆက်သွယ်ရန်နံပါတ်|Número de contacte|联系电话|Kontakt broj|Kontaktní číslo|Kontaktnummer|Contactnummer|Kontaktnumber|Numero ng contact|Yhteysnumero|Numéro de contact|საკონტაქტო ნომერი|Kontaktnummer|Αριθμός επικοινωνίας|સંપર્ક નંબર|Lambar tuntuɓa|מספר קשר|Elérhetőség|Símanúmer|Nọmba kọntaktị|Nomor kontak|Uimhir theagmhála|Numero di contatto|連絡先番号|Байланыс нөмірі|លេខទំនាក់ទំនង|연락처|ເບີຕິດຕໍ່|Kontakttālrunis|Kontaktinis numeris|Nombor hubungan|संपर्क क्रमांक|Холбоо барих дугаар|सम्पर्क नम्बर|Kontaktnummer|ଯୋଗାଯୋଗ ନମ୍ବର|د اړیکې شمېره|شماره تماس|Numer kontaktowy|Número de contato|ਸੰਪਰਕ ਨੰਬਰ|Număr de contact|Контактный номер|Контакт број|සම්බන්ධතා අංකය|Kontaktné číslo|Kontaktna številka|Lambarka xiriirka|Número de contacto|Nambari ya mawasiliano|Kontaktnummer|เบอร์ติดต่อ|İletişim numarası|Контактний номер|رابطہ نمبر|Aloqa raqami|Số liên hệ|Rhif cyswllt|Nọmba olubasọrọ|Inombolo yokuxhumana".split("|"))
add("selectLanguage", "Kies|ምረጥ|اختر|বাছনি কৰক|Seçin|নির্বাচন করুন|Изберете|ရွေးပါ|Selecciona|请选择|Odaberite|Vyberte|Vælg|Selecteer|Vali|Piliin|Valitse|Sélectionner|აირჩიეთ|Auswählen|Επιλογή|પસંદ કરો|Zaɓi|בחירה|Válasszon|Veldu|Họrọ|Pilih|Roghnaigh|Seleziona|選択|Таңдаңыз|ជ្រើសរើស|선택|ເລືອກ|Izvēlēties|Pasirinkti|Pilih|निवडा|Сонгох|छान्नुहोस्|Velg|ଚୟନ କରନ୍ତୁ|وټاکئ|انتخاب|Wybierz|Selecionar|ਚੁਣੋ|Selectați|Выбрать|Изаберите|තෝරන්න|Vyberte|Izberite|Dooro|Seleccionar|Chagua|Välj|เลือก|Seçin|Вибрати|منتخب کریں|Tanlang|Chọn|Dewis|Yan|Khetha".split("|"))
add("back", "Terug|ተመለስ|رجوع|পিছলৈ|Geri|পিছনে|Назад|နောက်သို့|Enrere|返回|Natrag|Zpět|Tilbage|Terug|Tagasi|Bumalik|Takaisin|Retour|უკან|Zurück|Πίσω|પાછળ|Baya|חזרה|Vissza|Til baka|Azụ|Kembali|Ar ais|Indietro|戻る|Артқа|ថយក្រោយ|뒤로|ກັບຄືນ|Atpakaļ|Atgal|Kembali|मागे|Буцах|पछाडि|Tilbake|ପଛକୁ|شاته|بازگشت|Wstecz|Voltar|ਪਿੱਛੇ|Înapoi|Назад|Назад|ආපසු|Späť|Nazaj|Dib|Atrás|Rudi|Tillbaka|กลับ|Geri|Назад|واپس|Orqaga|Quay lại|Yn ôl|Pada|Emuva".split("|"))
add("saveAndContinue", "Stoor en gaan voort|አስቀምጥ እና ቀጥል|حفظ ومتابعة|সংৰক্ষণ কৰি আগবাঢ়ক|Saxla və davam et|সংরক্ষণ করুন ও চালিয়ে যান|Запази и продължи|သိမ်းပြီး ဆက်လုပ်ပါ|Desa i continua|保存并继续|Spremi i nastavi|Uložit a pokračovat|Gem og fortsæt|Opslaan en doorgaan|Salvesta ja jätka|I-save at magpatuloy|Tallenna ja jatka|Enregistrer et continuer|შენახვა და გაგრძელება|Speichern und weiter|Αποθήκευση και συνέχεια|સાચવો અને આગળ વધો|Ajiye kuma ci gaba|שמירה והמשך|Mentés és folytatás|Vista og halda áfram|Chekwaa ma gaa n’ihu|Simpan dan lanjutkan|Sábháil agus lean ar aghaidh|Salva e continua|保存して続行|Сақтау және жалғастыру|រក្សាទុក ហើយបន្ត|저장하고 계속|ບັນທຶກແລ້ວສືບຕໍ່|Saglabāt un turpināt|Išsaugoti ir tęsti|Simpan dan teruskan|जतन करा आणि पुढे जा|Хадгалаад үргэлжлүүлэх|सुरक्षित गरेर अगाडि बढ्नुहोस्|Lagre og fortsett|ସଞ୍ଚୟ କରି ଜାରି ରଖନ୍ତୁ|خوندي کړئ او دوام ورکړئ|ذخیره و ادامه|Zapisz i kontynuuj|Salvar e continuar|ਸੰਭਾਲੋ ਅਤੇ ਜਾਰੀ ਰੱਖੋ|Salvează și continuă|Сохранить и продолжить|Сачувај и настави|සුරකින්න සහ ඉදිරියට|Uložiť a pokračovať|Shrani in nadaljuj|Kaydi oo sii wad|Guardar y continuar|Hifadhi na uendelee|Spara och fortsätt|บันทึกและดำเนินการต่อ|Kaydet ve devam et|Зберегти й продовжити|محفوظ کریں اور جاری رکھیں|Saqlash va davom etish|Lưu và tiếp tục|Cadw a pharhau|Fi pamọ ki o si tẹsiwaju|Londoloza uqhubeke".split("|"))
add("skipForNow", "Slaan vir nou oor|ለአሁን ዝለል|تخطي الآن|এতিয়া এৰি দিয়ক|İndi keç|এখন এড়িয়ে যান|Пропусни засега|ယခုကျော်မည်|Omet per ara|暂时跳过|Preskoči za sada|Přeskočit prozatím|Spring over for nu|Voor nu overslaan|Jäta praegu vahele|Laktawan muna|Ohita toistaiseksi|Passer pour l’instant|ახლა გამოტოვება|Vorerst überspringen|Παράλειψη προς το παρόν|હમણાં છોડો|Tsallake yanzu|דלג לעכשיו|Kihagyás most|Sleppa í bili|Maa ugbu a|Lewati dulu|Scipeáil anois|Salta per ora|今はスキップ|Әзірге өткізу|រំលងសិន|나중에 건너뛰기|ຂ້າມໄປກ່ອນ|Pagaidām izlaist|Praleisti dabar|Langkau buat masa ini|आत्ता वगळा|Одоогоор алгасах|अहिले छोड्नुहोस्|Hopp over nå|ଏବେ ଛାଡନ୍ତୁ|اوس پرېږدئ|فعلاً رد شوید|Pomiń na razie|Pular por agora|ਹੁਣੇ ਛੱਡੋ|Omite deocamdată|Пропустить сейчас|Прескочи за сада|දැනට මඟ හරින්න|Zatiaľ preskočiť|Preskoči za zdaj|Hada iska dhaaf|Omitir por ahora|Ruka kwa sasa|Hoppa över nu|ข้ามไปก่อน|Şimdilik atla|Пропустити зараз|ابھی چھوڑیں|Hozircha o‘tkazish|Bỏ qua lúc này|Hepgor am y tro|F’ọwọ silẹ fun bayi|Yeqa okwamanje".split("|"))
add("next", "Volgende|ቀጣይ|التالي|পৰৱর্তী|Növbəti|পরবর্তী|Напред|နောက်တစ်ခု|Següent|下一步|Dalje|Další|Næste|Volgende|Edasi|Susunod|Seuraava|Suivant|შემდეგი|Weiter|Επόμενο|આગળ|Na gaba|הבא|Tovább|Næsta|Ọzọ|Berikutnya|Ar aghaidh|Avanti|次へ|Келесі|បន្ទាប់|다음|ຕໍ່ໄປ|Tālāk|Toliau|Seterusnya|पुढे|Дараах|अर्को|Neste|ପରବର୍ତ୍ତୀ|بل|بعدی|Dalej|Próximo|ਅਗਲਾ|Înainte|Далее|Даље|ඊළඟ|Ďalej|Naprej|Xiga|Siguiente|Ifuatayo|Nästa|ถัดไป|İleri|Далі|اگلا|Keyingi|Tiếp theo|Nesaf|Tókàn|Okulandelayo".split("|"))
add("language", "Taal|ቋንቋ|اللغة|ভাষা|Dil|ভাষা|Език|ဘာသာစကား|Llengua|语言|Jezik|Jazyk|Sprog|Taal|Keel|Wika|Kieli|Langue|ენა|Sprache|Γλώσσα|ભાષા|Harshe|שפה|Nyelv|Tungumál|Asụsụ|Bahasa|Teanga|Lingua|言語|Тіл|ភាសា|언어|ພາສາ|Valoda|Kalba|Bahasa|भाषा|Хэл|भाषा|Språk|ଭାଷା|ژبه|زبان|Język|Idioma|ਭਾਸ਼ਾ|Limbă|Язык|Језик|භාෂාව|Jazyk|Jezik|Luqad|Idioma|Lugha|Språk|ภาษา|Dil|Мова|زبان|Til|Ngôn ngữ|Iaith|Ede|Ulimi".split("|"))
add("welcomeTitle", "Welkom, leier!|እንኳን ደህና መጡ መሪ!|مرحبًا أيها القائد!|স্বাগতম, নেতা!|Xoş gəldiniz, lider!|স্বাগতম, নেতা!|Добре дошли, лидере!|ကြိုဆိုပါတယ် ခေါင်းဆောင်|Benvingut, líder!|欢迎，领袖！|Dobrodošli, vođo!|Vítejte, lídře!|Velkommen, leder!|Welkom, leider!|Tere tulemast, juht!|Maligayang pagdating, lider!|Tervetuloa, johtaja!|Bienvenue, leader !|მოგესალმებით, ლიდერო!|Willkommen, Führungskraft!|Καλώς ορίσατε, ηγέτη!|સ્વાગત છે, નેતા!|Barka da zuwa, shugaba!|ברוך הבא, מנהיג!|Üdvözöljük, vezető!|Velkomin, leiðtogi!|Nnọọ, onye ndu!|Selamat datang, Pemimpin!|Fáilte, a cheannaire!|Benvenuto, leader!|ようこそ、リーダー！|Қош келдіңіз, көшбасшы!|សូមស្វាគមន៍ មេដឹកនាំ!|환영합니다, 리더!|ຍິນດີຕ້ອນຮັບ ຜູ້ນຳ!|Laipni lūdzam, līder!|Sveiki, lyderi!|Selamat datang, Pemimpin!|स्वागत आहे, नेता!|Тавтай морил, удирдагч!|स्वागत छ, नेता!|Velkommen, leder!|ସ୍ୱାଗତ, ନେତା!|ښه راغلاست مشره!|خوش آمدید، رهبر!|Witaj, liderze!|Bem-vindo, líder!|ਜੀ ਆਇਆਂ ਨੂੰ, ਲੀਡਰ!|Bun venit, liderule!|Добро пожаловать, лидер!|Добро дошли, вођо!|සාදරයෙන් පිළිගනිමු, නායකයා!|Vitajte, líder!|Dobrodošli, vodja!|Soo dhawoow, hoggaamiye!|¡Bienvenido, líder!|Karibu, kiongozi!|Välkommen, ledare!|ยินดีต้อนรับ ผู้นำ!|Hoş geldiniz, lider!|Вітаємо, лідере!|خوش آمدید، لیڈر!|Xush kelibsiz, lider!|Chào mừng, lãnh đạo!|Croeso, arweinydd!|Kaabo, oludari!|Siyakwamukela, mholi!".split("|"))
add("dashboard", "Kontroleskerm|ዳሽቦርድ|لوحة التحكم|ডেশ্ববৰ্ড|İdarə paneli|ড্যাশবোর্ড|Табло|ဒိုင်ခွက်|Tauler|仪表板|Nadzorna ploča|Přehled|Dashboard|Dashboard|Töölaud|Dashboard|Kojelauta|Tableau de bord|დაფა|Übersicht|Πίνακας|ડેશબોર્ડ|Dashboard|לוח בקרה|Irányítópult|Yfirlit|Dashboard|Dasbor|Deais|Dashboard|ダッシュボード|Басты бет|ផ្ទាំងគ្រប់គ្រង|대시보드|ໜ້າຫຼັກ|Panelis|Suvestinė|Papan pemuka|डॅशबोर्ड|Хяналтын самбар|ड्यासबोर्ड|Oversikt|ଡ୍ୟାସବୋର୍ଡ|ډشبورډ|داشبورد|Panel|Painel|ਡੈਸ਼ਬੋਰਡ|Panou|Панель|Контролна табла|උපකරණ පුවරුව|Prehľad|Nadzorna plošča|Dashboard|Panel|Dashibodi|Instrumentpanel|แดชบอร์ด|Kontrol paneli|Панель|ڈیش بورڈ|Boshqaruv paneli|Bảng điều khiển|Dangosfwrdd|Dasibodu|Ideshibhodi".split("|"))
add("goToDashboard", "Gaan na kontroleskerm|ወደ ዳሽቦርድ ሂድ|الانتقال إلى لوحة التحكم|ডেশ্ববৰ্ডলৈ যাওক|İdarə panelinə keç|ড্যাশবোর্ডে যান|Към таблото|ဒိုင်ခွက်သို့|Ves al tauler|前往仪表板|Idi na nadzornu ploču|Přejít na přehled|Gå til dashboard|Ga naar dashboard|Mine töölauale|Pumunta sa dashboard|Siirry kojelaudalle|Aller au tableau de bord|დაფაზე გადასვლა|Zur Übersicht|Μετάβαση στον πίνακα|ડેશબોર્ડ પર જાઓ|Je zu dashboard|מעבר ללוח הבקרה|Ugrás az irányítópultra|Fara á yfirlit|Gaa na dashboard|Ke dasbor|Téigh go dtí an deais|Vai alla dashboard|ダッシュボードへ|Басты бетке өту|ទៅផ្ទាំងគ្រប់គ្រង|대시보드로 이동|ໄປໜ້າຫຼັກ|Iet uz paneli|Eiti į suvestinę|Pergi ke papan pemuka|डॅशबोर्डवर जा|Хяналтын самбар руу|ड्यासबोर्डमा जानुहोस्|Gå til oversikten|ଡ୍ୟାସବୋର୍ଡକୁ ଯାଆନ୍ତୁ|ډشبورډ ته لاړ شئ|رفتن به داشبورد|Przejdź do panelu|Ir para o painel|ਡੈਸ਼ਬੋਰਡ ’ਤੇ ਜਾਓ|Mergi la panou|Перейти к панели|Иди на контролну таблу|උපකරණ පුවරුවට යන්න|Prejsť na prehľad|Pojdi na nadzorno ploščo|Aad dashboard|Ir al panel|Nenda kwenye dashibodi|Gå till instrumentpanelen|ไปที่แดชบอร์ด|Kontrol paneline git|Перейти до панелі|ڈیش بورڈ پر جائیں|Boshqaruv paneliga o‘tish|Đến bảng điều khiển|Mynd i’r dangosfwrdd|Lọ si dasibodu|Yiya kudeshibhodi".split("|"))
add("invalidContact", "Voer ’n geldige kontaknommer in.|ትክክለኛ የመገናኛ ቁጥር ያስገቡ።|أدخل رقم اتصال صالحًا.|এটা বৈধ যোগাযোগ নম্বৰ দিয়ক।|Düzgün əlaqə nömrəsi daxil edin.|একটি বৈধ যোগাযোগ নম্বর লিখুন।|Въведете валиден телефон.|မှန်ကန်သောဖုန်းနံပါတ်ထည့်ပါ။|Introdueix un número vàlid.|请输入有效的联系电话。|Unesite valjani kontakt broj.|Zadejte platné kontaktní číslo.|Indtast et gyldigt nummer.|Voer een geldig nummer in.|Sisestage kehtiv number.|Maglagay ng wastong numero.|Anna kelvollinen numero.|Saisissez un numéro valide.|შეიყვანეთ სწორი ნომერი|Geben Sie eine gültige Nummer ein.|Εισάγετε έγκυρο αριθμό.|માન્ય સંપર્ક નંબર દાખલ કરો.|Shigar da lambar tuntuɓa mai inganci.|הזינו מספר קשר תקין.|Adjon meg érvényes számot.|Sláðu inn gilt númer.|Tinye nọmba ziri ezi.|Masukkan nomor yang valid.|Cuir isteach uimhir bhailí.|Inserisci un numero valido.|有効な連絡先番号を入力してください。|Жарамды нөмір енгізіңіз។|បញ្ចូលលេខត្រឹមត្រូវ។|올바른 연락처를 입력하세요.|ໃສ່ເບີທີ່ຖືກຕ້ອງ.|Ievadiet derīgu numuru.|Įveskite tinkamą numerį.|Masukkan nombor yang sah.|वैध संपर्क क्रमांक टाका.|Зөв дугаар оруулна уу.|मान्य सम्पर्क नम्बर लेख्नुहोस्।|Skriv inn et gyldig nummer.|ବୈଧ ନମ୍ବର ଲେଖନ୍ତୁ।|سمه شمېره ولیکئ.|یک شماره معتبر وارد کنید.|Podaj prawidłowy numer.|Digite um número válido.|ਇੱਕ ਠੀਕ ਨੰਬਰ ਲਿਖੋ।|Introduceți un număr valid.|Введите действительный номер.|Унесите исправан број.|වලංගු අංකයක් ඇතුළත් කරන්න.|Zadajte platné číslo.|Vnesite veljavno številko.|Geli lambar sax ah.|Introduce un número válido.|Weka nambari halali.|Ange ett giltigt nummer.|ป้อนเบอร์ที่ถูกต้อง|Geçerli bir numara girin.|Введіть дійсний номер.|درست نمبر درج کریں۔|To‘g‘ri raqam kiriting.|Nhập số hợp lệ.|Rhowch rif dilys.|Tẹ nọmba to tọ.|Faka inombolo evumelekile.".split("|"))
add("invalidSelection", "Kies ’n geldige opsie.|ትክክለኛ አማራጭ ይምረጡ።|اختر خيارًا صالحًا.|এটা বৈধ বিকল্প বাছনি কৰক।|Düzgün seçim edin.|একটি বৈধ বিকল্প বেছে নিন।|Изберете валидна опция.|မှန်ကန်သောရွေးချယ်မှုလုပ်ပါ။|Tria una opció vàlida.|请选择有效选项。|Odaberite valjanu opciju.|Vyberte platnou možnost.|Vælg en gyldig mulighed.|Kies een geldige optie.|Valige kehtiv valik.|Pumili ng wastong opsyon.|Valitse kelvollinen vaihtoehto.|Choisissez une option valide.|აირჩიეთ სწორი ვარიანტი|Wählen Sie eine gültige Option.|Επιλέξτε έγκυρη επιλογή.|માન્ય વિકલ્પ પસંદ કરો.|Zaɓi zaɓi mai inganci.|בחרו אפשרות תקינה.|Válasszon érvényes lehetőséget.|Veldu gildan valkost.|Họrọ nhọrọ ziri ezi.|Pilih opsi yang valid.|Roghnaigh rogha bhailí.|Scegli un’opzione valida.|有効な選択肢を選んでください。|Жарамды нұсқаны таңдаңыз.|ជ្រើសរើសជម្រើសត្រឹមត្រូវ។|올바른 옵션을 선택하세요.|ເລືອກທາງເລືອກທີ່ຖືກຕ້ອງ.|Izvēlieties derīgu opciju.|Pasirinkite tinkamą parinktį.|Pilih pilihan yang sah.|वैध पर्याय निवडा.|Зөв сонголт хийнэ үү.|मान्य विकल्प छान्नुहोस्।|Velg et gyldig alternativ.|ବୈଧ ବିକଳ୍ପ ବାଛନ୍ତୁ।|سمه انتخاب وکړئ.|یک گزینه معتبر انتخاب کنید.|Wybierz prawidłową opcję.|Escolha uma opção válida.|ਇੱਕ ਠੀਕ ਵਿਕਲਪ ਚੁਣੋ।|Alegeți o opțiune validă.|Выберите действительный вариант.|Изаберите исправну опцију.|වලංගු විකල්පයක් තෝරන්න.|Vyberte platnú možnosť.|Izberite veljavno možnost.|Dooro doorasho sax ah.|Elige una opción válida.|Chagua chaguo halali.|Välj ett giltigt alternativ.|เลือกตัวเลือกที่ถูกต้อง|Geçerli bir seçenek seçin.|Виберіть дійсний варіант.|درست اختیار منتخب کریں۔|To‘g‘ri variantni tanlang.|Chọn một tùy chọn hợp lệ.|Dewiswch opsiwn dilys.|Yan aṣayan to tọ.|Khetha okukhethwayo okuvumelekile.".split("|"))
add("descriptor", "POLITIKUS-VERSNELLERPLATFORM|የፖለቲከኛ ማፍጠኛ መድረክ|منصة تسريع السياسيين|ৰাজনীতিবিদ ত্বৰক মঞ্চ|Siyasətçi sürətləndirici platforması|রাজনীতিবিদ ত্বরক মঞ্চ|Платформа за политици|နိုင်ငံရေးသမား အရှိန်မြှင့်စင်|Plataforma acceleradora de polítics|政治家加速平台|Platforma za političare|Platforma pro politiky|Politikeraccelerator|Politicusversneller|Poliitikute kiirendi|Platform ng pulitiko|Poliitikkoalusta|Plateforme d’accélération politique|პოლიტიკოსის პლატფორმა|Politiker-Beschleuniger|Πλατφόρμα πολιτικών|રાજકારણી પ્રવેગક મંચ|Dandalin mai siyasa|פלטפורמת האצה לפוליטיקאים|Politikusgyorsító|Vettvangur stjórnmálamanna|Ikpo okwu ndọrọ ndọrọ|Platform akselerator politisi|Ardán polaiteoirí|Piattaforma per politici|政治家アクセラレーター|Саясаткер платформасы|វេទិកាអ្នកនយោបាយ|정치인 가속 플랫폼|ແພລດຟອມນັກການເມືອງ|Politiskā platforma|Politikų platforma|Platform pemecut ahli politik|राजकारणी प्रवेगक व्यासपीठ|Улс төрчийн платформ|राजनीतिज्ञ त्वरक मञ्च|Politikerplattform|ରାଜନେତା ତ୍ୱରକ ମଞ୍ଚ|د سیاستوال چټکونکی|سکوی شتاب سیاسی|Platforma polityków|Plataforma de políticos|ਸਿਆਸਤਦਾਨ ਐਕਸਲਰੇਟਰ|Platformă pentru politicieni|Платформа для политиков|Платформа за политичаре|දේශපාලනඥ වේදිකාව|Platforma pre politikov|Platforma za politike|Madal siyaasi|Plataforma de políticos|Jukwaa la wanasiasa|Politikerplattform|แพลตฟอร์มนักการเมือง|Siyasetçi hızlandırıcı|Платформа для політиків|سیاستدان ایکسلریٹر|Siyosatchi platformasi|Nền tảng chính trị gia|Platfform gwleidyddion|Sakani oloselu|Isikhungo sezombusazwe".split("|"))
add("domainTitle", "Domeinnaam soek|የዶሜይን ስም ፍለጋ|بحث اسم النطاق|ড’মেইন নাম সন্ধান|Domen adı axtarışı|ডোমেইন নাম খোঁজ|Търсене на домейн|ဒိုမိန်းရှာရန်|Cerca de domini|域名搜索|Pretraga domene|Hledání domény|Domænesøgning|Domeinnaam zoeken|Domeeninime otsing|Paghahanap ng domain|Verkkotunnushaku|Recherche de domaine|დომენის ძიება|Domainnamen-Suche|Αναζήτηση domain|ડોમેન નામ શોધ|Neman sunan domain|חיפוש שם דומיין|Domainkeresés|Lénaleit|Chọọ aha domain|Cari nama domain|Cuardach fearainn|Ricerca dominio|ドメイン名検索|Домен іздеу|ស្វែងរកដែន|도메인 검색|ຄົ້ນຫາໂດເມນ|Domēna meklēšana|Domeno paieška|Carian nama domain|डोमेन नाव शोध|Домен хайх|डोमेन नाम खोज|Domenesøk|ଡୋମେନ୍ ସନ୍ଧାନ|ډومین لټون|جستجوی دامنه|Wyszukiwanie domeny|Busca de domínio|ਡੋਮੇਨ ਖੋਜ|Căutare domeniu|Поиск домена|Претрага домена|ඩොමේන් සෙවීම|Hľadanie domény|Iskanje domene|Raadinta domain|Búsqueda de dominio|Utafutaji wa kikoa|Domänsökning|ค้นหาโดเมน|Alan adı arama|Пошук домену|ڈومین تلاش|Domen qidiruv|Tìm tên miền|Chwilio parth|Wiwa orukọ ibugbe|Ukusesha kwesizinda".split("|"))
add("searchPlaceholder", "Soek jou naam|ስምዎን ይፈልጉ|ابحث عن اسمك|আপোনাৰ নাম বিচাৰক|Adınızı axtarın|আপনার নাম খুঁজুন|Потърсете името си|သင့်နာမည်ကိုရှာပါ|Cerca el teu nom|搜索你的名字|Pretražite svoje ime|Hledejte své jméno|Søg dit navn|Zoek je naam|Otsi oma nime|Hanapin ang pangalan mo|Hae nimeäsi|Recherchez votre nom|მოძებნეთ თქვენი სახელი|Suchen Sie Ihren Namen|Αναζητήστε το όνομά σας|તમારું નામ શોધો|Nemi sunanka|חפשו את שמכם|Keresse a nevét|Leitaðu að nafninu|Chọọ aha gị|Cari nama Anda|Cuardaigh d’ainm|Cerca il tuo nome|名前を検索|Атыңызды іздеңіз|ស្វែងរកឈ្មោះអ្នក|이름을 검색하세요|ຄົ້ນຫາຊື່ຂອງທ່ານ|Meklējiet savu vārdu|Ieškokite savo vardo|Cari nama anda|तुमचे नाव शोधा|Нэрээ хайна уу|आफ्नो नाम खोज्नुहोस्|Søk navnet ditt|ଆପଣଙ୍କ ନାମ ଖୋଜନ୍ତୁ|خپل نوم ولټوئ|نام خود را جستجو کنید|Wyszukaj swoje imię|Pesquise seu nome|ਆਪਣਾ ਨਾਮ ਲੱਭੋ|Căutați numele|Найдите своё имя|Потражите своје име|ඔබේ නම සොයන්න|Hľadajte svoje meno|Poiščite svoje ime|Raadi magacaaga|Busca tu nombre|Tafuta jina lako|Sök ditt namn|ค้นหาชื่อของคุณ|Adınızı arayın|Знайдіть своє ім’я|اپنا نام تلاش کریں|Ismingizni qidiring|Tìm tên của bạn|Chwiliwch eich enw|Wa orukọ rẹ|Sesha igama lakho".split("|"))
add("available", "Beskikbaar|ይገኛል|متاح|উপলব্ধ|Əlçatan|উপলব্ধ|Налично|ရနိုင်သည်|Disponible|可用|Dostupno|Dostupné|Tilgængelig|Beschikbaar|Saadaval|Available|Saatavilla|Disponible|ხელმისაწვდომი|Verfügbar|Διαθέσιμο|ઉપલબ્ધ|Akwai|זמין|Elérhető|Laust|Dị|Tersedia|Ar fáil|Disponibile|利用可能|Қолжетімді|មាន|사용 가능|ມີ|Pieejams|Prieinama|Tersedia|उपलब्ध|Боломжтой|उपलब्ध|Tilgjengelig|ଉପଲବ୍ଧ|شته|موجود|Dostępne|Disponível|ਉਪਲਬਧ|Disponibil|Доступно|Доступно|ලබා ගත හැක|Dostupné|Na voljo|Diyaar|Disponible|Inapatikana|Tillgänglig|พร้อมใช้|Uygun|Доступно|دستیاب|Mavjud|Có sẵn|Ar gael|Wa|Iyatholakala".split("|"))
add("add", "Voeg by|ጨምር|إضافة|যোগ কৰক|Əlavə et|যোগ করুন|Добави|ထည့်|Afegeix|添加|Dodaj|Přidat|Tilføj|Toevoegen|Lisa|Idagdag|Lisää|Ajouter|დამატება|Hinzufügen|Προσθήκη|ઉમેરો|Ƙara|הוסף|Hozzáadás|Bæta við|Tinye|Tambah|Cuir leis|Aggiungi|追加|Қосу|បន្ថែម|추가|ເພີ່ມ|Pievienot|Pridėti|Tambah|जोडा|Нэмэх|थप्नुहोस्|Legg til|ଯୋଡନ୍ତୁ|زیات کړئ|افزودن|Dodaj|Adicionar|ਜੋੜੋ|Adaugă|Добавить|Додај|එක් කරන්න|Pridať|Dodaj|Ku dar|Añadir|Ongeza|Lägg till|เพิ่ม|Ekle|Додати|شامل کریں|Qo‘shish|Thêm|Ychwanegu|Fi kun|Engeza".split("|"))
add("selected", "Gekies|ተመርጧል|محدد|নিৰ্বাচিত|Seçildi|নির্বাচিত|Избрано|ရွေးပြီး|Seleccionat|已选择|Odabrano|Vybráno|Valgt|Geselecteerd|Valitud|Napili|Valittu|Sélectionné|არჩეული|Ausgewählt|Επιλεγμένο|પસંદ|An zaɓa|נבחר|Kiválasztva|Valið|Ahọpụtara|Dipilih|Roghnaithe|Selezionato|選択済み|Таңдалды|បានជ្រើស|선택됨|ເລືອກແລ້ວ|Izvēlēts|Pasirinkta|Dipilih|निवडले|Сонгосон|छानिएको|Valgt|ଚୟନିତ|ټاکل شوی|انتخاب‌شده|Wybrano|Selecionado|ਚੁਣਿਆ|Selectat|Выбрано|Изабрано|තෝරා ඇත|Vybrané|Izbrano|La doortay|Seleccionado|Imechaguliwa|Vald|เลือกแล้ว|Seçildi|Вибрано|منتخب|Tanlandi|Đã chọn|Wedi dewis|Ti yan|Okukhethiwe".split("|"))
add("comingLater", "Kom later|በኋላ ይመጣል|قادم لاحقًا|পিছত আহিব|Sonra gələcək|পরে আসছে|Очаквайте|နောက်မှလာမည်|Aviat|即将推出|Uskoro|Již brzy|Kommer senere|Komt later|Tuleb hiljem|Darating|Tulossa|Bientôt|მოგვიანებით|Kommt später|Σύντομα|પછી આવશે|Daga baya|בקרוב|Hamarosan|Seinna|Emechaa|Nanti|Ar ball|In arrivo|後日|Кейін|ពេលក្រោយ|나중에|ພາຍຫຼັງ|Vēlāk|Vėliau|Akan datang|नंतर येईल|Дараа|पछि आउँछ|Kommer senere|ପରେ ଆସିବ|وروسته|به‌زودی|Wkrótce|Em breve|ਬਾਅਦ ਵਿੱਚ|În curând|Позже|Ускоро|පසුව|Neskôr|Kmalu|Dambe|Próximamente|Inakuja|Kommer senare|ภายหลัง|Yakında|Пізніше|جلد آ رہا ہے|Keyinroq|Sắp có|Yn nes ymlaen|Ní bá yìí|Kuyeza".split("|"))

out = []
out.append("const wideTranslations = <String, Map<String, String>>{")
for index, code in enumerate(langs):
    out.append(f"  '{code}': {{")
    for key, values in packs.items():
        text = values[index].replace("\\", "\\\\").replace("'", "\\'")
        out.append(f"    '{key}': '{text}',")
    out.append("  },")
out.append("};")
out.append("")

target = "lib/app/localization/translations/wide.dart"
with open(target, "w", encoding="utf-8") as handle:
    handle.write("\n".join(out))
print(f"wrote {target} languages={len(langs)} keys={len(packs)}")
